// Auto-generated by gulp-svg-sprites

@mixin svg($name, $pseudo: false, $display: inline-block) {
	@if($pseudo) {
		&:#{$pseudo} {
			content: ' ';
			@include svg-content($name, $display);
		}
	} @else {
		@include svg-content($name, $display);
	}
}

@mixin svg-content($name, $display: inline-block) {
	background: url('../images/sprite.svg') no-repeat;
	background-size: {{#pxToEm}}{{spriteWidth}}{{/pxToEm}} {{#pxToEm}}{{spriteHeight}}{{/pxToEm}};
	display: $display;

	@if map-has-key($svgs, $name) {
		$svg: map-get($svgs, $name);

		background-position: map-get($svg, background-position);
		height: map-get($svg, height);
		width: map-get($svg, width);
	} @else {
		@warn "The SVG sprite `#{$name}` was not found.";
	}
}

@mixin svg-position($name) {
	@if map-has-key($svgs, $name) {
		$svg: map-get($svgs, $name);

		background-position: map-get($svg, background-position);
	} @else {
		@warn "The SVG sprite `#{$name}` was not found.";
	}
}

$svgs: (
{{#shapes}}
	{{name}}: (
		background-position: {{#pxToEmPosition}}{{position.absolute.x}}{{/pxToEmPosition}} {{#pxToEmPosition}}{{position.absolute.y}}{{/pxToEmPosition}},
		width: {{#pxToEm}}{{width.inner}}{{/pxToEm}},
		height: {{#pxToEm}}{{height.inner}}{{/pxToEm}},
	){{^last}},{{/last}}
{{/shapes}}
);
